function throwErr(err: string, codeX: number): never { // never: c처digo que n찾o finalizou -- void: c처digo que n찾o retorna
    throw {error: err, code: codeX}
}

throwErr("Unexpected error", 500);